apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: channel
  namespace: app-a 
spec:
  pathname: https://github.com/achieris/gitops-examples.git
  type: Git

